name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: macos-26
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: ./.github/actions/setup-mint
    - name: Run swiftlint
      id: swiftlint
      continue-on-error: true
      run: make lint-swiftlint
    - name: Run swiftformat
      id: swiftformat
      continue-on-error: true
      run: make lint-swiftformat
    - name: Run test
      id: test
      continue-on-error: true
      run: make test
    - name: set workflow status
      if: ${{ steps.swiftlint.outcome == 'failure' || steps.swiftformat.outcome == 'failure' || steps.test.outcome == 'failure' }}
      run: exit 1
