name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: ./.github/actions/setup-mint
    - name: Run tests
      run: make test

  lint:
    runs-on: ubuntu-slim
    steps:
    - name: Setup Swift to use in Mint
      uses: swift-actions/setup-swift@7ca6abe6b3b0e8b5421b88be48feee39cbf52c6a # v2.4.0
      with:
        swift-version: '6.2'
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: ./.github/actions/setup-mint
    - name: Lint
      run: make lint

