name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: Asia/Tokyo

jobs:
  check:
    runs-on: macos-26
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        lfs: true
    - uses: ./.github/actions/setup-mint
    - name: Run swiftlint
      id: swiftlint
      continue-on-error: true
      run: make lint-swiftlint
    - name: Run swiftformat
      id: swiftformat
      continue-on-error: true
      run: make lint-swiftformat
    - name: Run test
      id: test
      continue-on-error: true
      run: make test
    - name: set workflow status
      if: ${{ steps.swiftlint.outcome == 'failure' || steps.swiftformat.outcome == 'failure' || steps.test.outcome == 'failure' }}
      run: exit 1
